services:
  - type: web
    name: dhont-simulator
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
