services:
  - type: static
    name: dhont-simulator
    plan: free
    branch: main
    buildCommand: npm ci && npm run build
    publishDir: dist
    envVars:
      - key: NODE_ENV
        value: production
